add_newline = true # remove a line at top

[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

[golang]
symbol = "🏎💨 "

[directory]
style = "fg:#98C379"

[aws]
disabled = true

[conda]
disabled = true

[crystal]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[haskell]
disabled = true

[julia]
disabled = true

[package]
disabled = true

[ocaml]
disabled = true

[php]
disabled = true

[rust]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[zig]
disabled = true
